@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.eevneon.radiationfission.content.rtg;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;